name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Rust:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - run: |
        ${{ secrets.LINKS }}
        cargo build --release
    - name: Upload syatisetup
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{matrix.os}}
        path: target/release/syatisetup.exe
    - name: Upload syatisetup
      uses: actions/upload-artifact@v3.1.2
      if: runner.os != 'Windows'
      with:
          name: ${{matrix.os}}
          path: target/release/syatisetup

  Publish:
    needs: Build-Rust
    if: github.event_name == 'push'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4.1.7
      with: 
        name: windows-latest
        path: ${{ github.workspace }}
    - uses: actions/download-artifact@v4.1.7
      with: 
          name: ubuntu-latest
          path: ${{ github.workspace }}
    -  run: ren syatisetup syatisetup-linux
    - uses: actions/download-artifact@v4.1.7
      with:
        name: macos-latest
        path: ${{github.workspace}}
    - run: ren syatisetup syatisetup-macos
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
          syatisetup*
